services:
  mongodb:
    image: mongo:6
    container_name: ordoro-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: ordoro

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    container_name: ordoro-backend-dev
    environment:
      MONGO_URI: mongodb://mongodb:27017/ordoro
      NODE_ENV: development
    volumes:
      - ./Back-end:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    # If you install nodemon (npm i -D nodemon) update command to: nodemon server.js
    command: sh -c "npm install && npm start"

  frontend:
    image: node:18-alpine
    container_name: ordoro-frontend-dev
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      - ./Frount-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm install && npm start"

volumes:
  mongo_data_dev:
  backend_node_modules:
  frontend_node_modules:
